{
  "schema_version": "1.0",
  "workflow_version": "0.1.0a0",
  "active_contract_version": 1,
  "project_contract_versions": [
    {
      "schema_version": "1.0",
      "contract_version": 1,
      "project_id": "project_e8a619ec1cadbfd2247ea407",
      "indication": "特应性皮炎",
      "reports": [
        "C"
      ],
      "outputs": [
        "html"
      ],
      "timezone": "Asia/Shanghai",
      "data_cutoff": "2026-07-31T23:59:59.999999+08:00",
      "cutoff_was_user_supplied": true,
      "created_at": "2026-09-01T15:01:26.989699+08:00"
    }
  ]
}
