"""A 类报告范围、成熟度与 result-bearing 证据模型。

对外公开：A 项目合同与成熟度分层字段规格（``contracts``）、成熟度分层与
逐层必需字段判定（``analysis``）。成熟度与 result-bearing 直接消费 Phase 3
已接受的宇宙快照与证据绑定；本包只实现与测试不可变业务合同，不生成报告
或占位物。
"""

from ci_workflow.reports.a.analysis import (
    BlockingExplanation,
    FieldOutcome,
    FieldVerdict,
    MaturityGateResult,
    UniverseAnalysisResult,
    UniverseProjectResult,
    analyze_universe,
    determine_maturity_level,
    evaluate_maturity_gate,
)
from ci_workflow.reports.a.contracts import (
    ANCHOR_TRIAL,
    CHINA_STAGE_STATUS_DATE,
    CORE_EFFICACY_RECORD,
    CORE_TRIAL_DEVELOPMENT_ROLE,
    CORE_TRIAL_IDENTITY,
    CORE_TRIAL_STATUS,
    DEVELOPER_ORIGINATOR,
    INDICATION_RELATION,
    MODALITY,
    OVERSEAS_STAGE_STATUS_DATE,
    REGULATORY_EVENT,
    REGULATORY_EVENT_DATE,
    REGULATORY_EVENT_JURISDICTION,
    REQUIRED_FIELD_SPECS,
    SAFETY_SUMMARY_RECORD,
    TARGET_MECHANISM,
    AnchorTrialRecord,
    AProjectContract,
    CoreTrialRecord,
    CoreTrialRole,
    MaturityLevel,
    RegionDevelopment,
    RegistryResultsPostedEvidence,
    RegulatoryEventKind,
    RegulatoryEventRecord,
    RequiredFieldKey,
    RequiredFieldSpec,
    SafetyEventUnitId,
    SafetyMeasurementUnit,
    assert_ladder_monotonic,
    required_fields_for,
)

__all__ = [
    "ANCHOR_TRIAL",
    "AProjectContract",
    "AnchorTrialRecord",
    "BlockingExplanation",
    "CHINA_STAGE_STATUS_DATE",
    "CORE_EFFICACY_RECORD",
    "CORE_TRIAL_DEVELOPMENT_ROLE",
    "CORE_TRIAL_IDENTITY",
    "CORE_TRIAL_STATUS",
    "CoreTrialRecord",
    "CoreTrialRole",
    "DEVELOPER_ORIGINATOR",
    "FieldOutcome",
    "FieldVerdict",
    "INDICATION_RELATION",
    "MODALITY",
    "MaturityGateResult",
    "MaturityLevel",
    "OVERSEAS_STAGE_STATUS_DATE",
    "REGULATORY_EVENT",
    "REGULATORY_EVENT_DATE",
    "REGULATORY_EVENT_JURISDICTION",
    "REQUIRED_FIELD_SPECS",
    "RegionDevelopment",
    "RegistryResultsPostedEvidence",
    "RegulatoryEventKind",
    "RegulatoryEventRecord",
    "RequiredFieldKey",
    "RequiredFieldSpec",
    "SAFETY_SUMMARY_RECORD",
    "SafetyEventUnitId",
    "SafetyMeasurementUnit",
    "TARGET_MECHANISM",
    "UniverseAnalysisResult",
    "UniverseProjectResult",
    "analyze_universe",
    "assert_ladder_monotonic",
    "determine_maturity_level",
    "evaluate_maturity_gate",
    "required_fields_for",
]
