"""Task 9.4 宿主适配层：共享合同与 Codex/Hermes/OMP 薄适配器。

适配器只做调用映射与运行身份定位；语义一致性由 ``HostSemanticReceipt``
比较面和公共 capability preflight / 事件 / 检查点保证。
"""

from __future__ import annotations

from ci_workflow.hosts.base import (
    CANONICAL_STATE_MESSAGES_ZH,
    DOWNLOAD_STATE_LABELS_ZH,
    FORBIDDEN_HOST_OPERATIONS,
    HOST_ADAPTER_NAMES,
    HOST_ADAPTER_PUBLIC_API,
    HOST_RUN_IDENTITY_HOOKS,
    HOST_SHARED_SEMANTIC_SURFACE,
    BlockingAndRecovery,
    CanonicalProjectState,
    CapabilitySelectionSummary,
    CapabilityStateRecord,
    DeliveredArtifact,
    DeliveryReadinessRecord,
    FailureClass,
    HostAdapter,
    HostBoundaryError,
    HostInvocationPlan,
    HostRunIdentity,
    HostSemanticReceipt,
    ManualInboxPendingItem,
    MinimalUserInput,
    PartialDeliverySummary,
    PendingReportOutput,
    ResearchReadinessRecord,
)
from ci_workflow.hosts.codex import CodexHostAdapter
from ci_workflow.hosts.hermes import HermesHostAdapter
from ci_workflow.hosts.omp import OmpHostAdapter
from ci_workflow.hosts.receipt import (
    RECEIPT_KIND,
    HostArtifactBinding,
    HostEntryBinding,
    HostEventChainBinding,
    HostExecutableEvidence,
    HostFixtureBinding,
    HostManifestBinding,
    HostPackageBinding,
    HostProcessBinding,
    HostReceipt,
    HostReceiptHost,
    HostReceiptIntegrityError,
    HostReceiptRunState,
    HostReceiptStatus,
    HostRunEvidence,
    HostRunOutcome,
    HostSessionBinding,
    build_host_receipt,
)

__all__ = [
    "BlockingAndRecovery",
    "CANONICAL_STATE_MESSAGES_ZH",
    "CanonicalProjectState",
    "CapabilitySelectionSummary",
    "CapabilityStateRecord",
    "CodexHostAdapter",
    "DeliveredArtifact",
    "DeliveryReadinessRecord",
    "DOWNLOAD_STATE_LABELS_ZH",
    "FailureClass",
    "FORBIDDEN_HOST_OPERATIONS",
    "HermesHostAdapter",
    "HOST_ADAPTER_NAMES",
    "HOST_ADAPTER_PUBLIC_API",
    "HOST_RUN_IDENTITY_HOOKS",
    "HOST_SHARED_SEMANTIC_SURFACE",
    "HostAdapter",
    "HostArtifactBinding",
    "HostBoundaryError",
    "HostEntryBinding",
    "HostEventChainBinding",
    "HostExecutableEvidence",
    "HostFixtureBinding",
    "HostInvocationPlan",
    "HostManifestBinding",
    "HostPackageBinding",
    "HostProcessBinding",
    "HostReceipt",
    "HostReceiptHost",
    "HostReceiptIntegrityError",
    "HostReceiptRunState",
    "HostReceiptStatus",
    "HostRunEvidence",
    "HostRunIdentity",
    "HostRunOutcome",
    "HostSemanticReceipt",
    "HostSessionBinding",
    "ManualInboxPendingItem",
    "MinimalUserInput",
    "OmpHostAdapter",
    "PartialDeliverySummary",
    "PendingReportOutput",
    "RECEIPT_KIND",
    "ResearchReadinessRecord",
    "build_host_receipt",
]
